server:
  port: 7000

app:
  datasource:
    # PostgreSQL DB - "ordermanager"
    data:
      jdbc-url : jdbc:postgresql://localhost:5432/ordermanager
      username : postgres
      password : ciao1234

    # PostgreSQL DB - "ordermanager-login"
    login:
      jdbc-url : jdbc:postgresql://localhost:5432/ordermanager-login
      username : postgres
      password : ciao1234

graphql:
  servlet:
    cors:
      allowed-headers: "*"
      allowed-methods: POST
      allowed-origins:
        - "*"

